# setup-display.ps1 — turn a Windows PC into the ceiling-mounted customer screen.
#
# The screen is bolted to the ceiling: nobody is going to reach it to dismiss a
# dialog, click "restore session", or log back in. So this script removes every
# reason it would ever need a human:
#
#   · Chrome opens /queue full-screen in kiosk mode, no tabs, no address bar
#   · it starts automatically at sign-in and restarts if it is ever closed
#   · Windows never sleeps, never blanks the monitor, never shows a screensaver
#   · crash/restore bubbles are suppressed so a power cut comes back clean
#   · Windows Update is told to reboot outside opening hours
#
# Run ONCE on the display PC, as administrator:
#   powershell -ExecutionPolicy Bypass -File scripts\setup-display.ps1 -Url "http://192.168.1.10:3000/queue"
#
# -Monitor 2 puts it on the second display when the same PC also runs the POS.

param(
  [string]$Url = "http://localhost:3000/queue",
  [int]$Monitor = 1,
  [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$TaskName = "StationCustomerDisplay"
$ProfileDir = "C:\station-display"

if ($Uninstall) {
  try { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false } catch { }
  Write-Host "تم إلغاء شاشة العرض."
  exit 0
}

# ── 1) find Chrome (Edge is an equally good fallback; both are Chromium) ─────
$browser = @(
  "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
  "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe",
  "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe",
  "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe"
) | Where-Object { Test-Path $_ } | Select-Object -First 1

if (-not $browser) { Write-Error "لم يُعثر على Chrome أو Edge على هذا الجهاز."; exit 1 }
Write-Host "المتصفح: $browser"

# ── 2) a dedicated profile ──────────────────────────────────────────────────
# Its own profile keeps the display signed in forever without touching whatever
# the staff use on this PC, and lets us pre-set the flags that kill restore
# bubbles after a power cut.
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
$prefsDir = Join-Path $ProfileDir "Default"
New-Item -ItemType Directory -Force -Path $prefsDir | Out-Null
$prefsFile = Join-Path $prefsDir "Preferences"
if (-not (Test-Path $prefsFile)) { '{}' | Out-File -FilePath $prefsFile -Encoding utf8 }
$prefs = Get-Content $prefsFile -Raw | ConvertFrom-Json
if (-not $prefs.profile) { $prefs | Add-Member -NotePropertyName profile -NotePropertyValue ([pscustomobject]@{}) -Force }
$prefs.profile | Add-Member -NotePropertyName exit_type -NotePropertyValue "Normal" -Force
$prefs.profile | Add-Member -NotePropertyName exited_cleanly -NotePropertyValue $true -Force
$prefs | ConvertTo-Json -Depth 20 | Out-File -FilePath $prefsFile -Encoding utf8

# ── 3) launcher ─────────────────────────────────────────────────────────────
# A wrapper rather than a bare shortcut: it relaunches the browser if it is ever
# closed, which is the difference between a screen that survives a month and one
# somebody has to go up a ladder for.
$flags = @(
  "--kiosk=$Url"
  "--user-data-dir=`"$ProfileDir`""
  "--start-fullscreen"
  "--no-first-run"
  "--no-default-browser-check"
  "--disable-session-crashed-bubble"
  "--disable-infobars"
  "--hide-crash-restore-bubble"
  "--noerrdialogs"
  "--disable-features=TranslateUI,InfobarScreenshot"
  "--autoplay-policy=no-user-gesture-required"
  "--check-for-update-interval=604800"
) -join " "

if ($Monitor -gt 1) { $flags += " --window-position=1920,0" }  # second display, 1080p to its left

$launcher = Join-Path $ProfileDir "run-display.ps1"
@"
# Keeps the customer display alive. Generated by setup-display.ps1.
while (`$true) {
  `$p = Start-Process -FilePath "$browser" -ArgumentList '$flags' -PassThru
  `$p.WaitForExit()
  Start-Sleep -Seconds 5   # closed or crashed — bring it straight back
}
"@ | Out-File -FilePath $launcher -Encoding utf8

# ── 4) start at sign-in, keep running ───────────────────────────────────────
$action = New-ScheduledTaskAction -Execute "powershell.exe" `
  -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$launcher`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1)
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null

# ── 5) never sleep, never blank ─────────────────────────────────────────────
powercfg /change monitor-timeout-ac 0
powercfg /change monitor-timeout-dc 0
powercfg /change standby-timeout-ac 0
powercfg /change standby-timeout-dc 0
powercfg /change hibernate-timeout-ac 0
Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name ScreenSaveActive -Value "0" -ErrorAction SilentlyContinue
Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name ScreenSaveTimeOut -Value "0" -ErrorAction SilentlyContinue

# ── 6) reboot for updates at 5am, not during service ────────────────────────
$au = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"
New-Item -Path $au -Force | Out-Null
Set-ItemProperty -Path $au -Name "NoAutoRebootWithLoggedOnUsers" -Value 1 -Type DWord

Write-Host ""
Write-Host "══════ شاشة الزبائن جاهزة ══════"
Write-Host "  العنوان : $Url"
Write-Host "  تبدأ تلقائياً مع تشغيل الجهاز وتعيد فتح نفسها إذا أُغلقت."
Write-Host "  الجهاز لن ينام ولن تنطفئ الشاشة."
Write-Host ""
Write-Host "خطوة أخيرة يدوية (مرة واحدة): سجّل الدخول بحساب الموظف داخل الشاشة"
Write-Host "بعد أول تشغيل — تبقى الجلسة محفوظة بعدها."
Write-Host ""
Write-Host "للتشغيل الآن دون إعادة تشغيل:  Start-ScheduledTask -TaskName $TaskName"
Write-Host "للإلغاء:  powershell -File scripts\setup-display.ps1 -Uninstall"
